server:
  port: 8801

spring:
  boot:
    admin:
      client:
        url: "http://localhost:8788"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: debug


